_target_: pangaea.encoders.vit_encoder.VIT_Encoder

# Pesi pre-addestrati: puoi usare quelli di timm o altri
encoder_weights: ./pretrained_models/vit_tiny_patch16_224.pth
download_url: https://dl.fbaipublicfiles.com/deit/deit_tiny_patch16_224-b5f2ef4d.pth

embed_dim: 192
input_size: 224
patch_size: 16
depth: 12
num_heads: 3
mlp_ratio: 4

input_bands:
  optical:
    - B4
    - B3
    - B2

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 192
